apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: qsan-csi-pvc-snap
spec:
  volumeSnapshotClassName: qsan-xevo-snapclass
  source:
    persistentVolumeClaimName: qsan-csi-pvc