apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qsan-csi-pvc-restore
spec:
  storageClassName: qsan-xevo-storage
  dataSource:
    name: qsan-csi-pvc-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi