apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qsan
secretGenerator:
- name: qsan-auth-secret
  files:
  - qsan-auth.yaml
resources:
  - driverinfo.yaml
  - namespace.yaml
  - rbac.yaml
  - controller.yaml
  - node.yaml