apiVersion: v1
kind: Service
metadata:
  name: nginx-sts
  labels:
    app: nginx-sts
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
    protocol: TCP
    name: web
  selector:
    app: nginx-sts

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx-sts
  serviceName: nginx-sts
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-pvc
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: nginx-pvc
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: qsan-xevo-storage
      resources:
        requests:
          storage: 5Gi

